### ISSUE TITLE
BeanValidation: NotNull test is failing

### ISSUE THREAD

**Issue by rmpestano** [manorrock/jakartaee-examples#4] opened 2018-09-06 19:30 UTC
I'm getting following error when I ran **[NotNullBeanTest](https://github.com/manorrock/jakartaee-examples/blob/4a96ca7c83a82c70d3870635221d647e1553e917/beanvalidation/notNull/src/test/java/jakartaee/examples/beanvalidation/notnull/NotNullBeanTest.java#L91)**:

```
 Running jakartaee.examples.beanvalidation.notnull.NotNullBeanTest
Starting container using command: [java, -jar, /home/PROCERGS.REDERS/rafael-pestano/projetos/jakartaee-examples-master/target/payara5/glassfish/modules/admin-cli.jar, start-domain, -t]
Successfully started the domain : domain1
domain  Location: /home/PROCERGS.REDERS/rafael-pestano/projetos/jakartaee-examples-master/target/payara5/glassfish/domains/domain1
Log File: /home/PROCERGS.REDERS/rafael-pestano/projetos/jakartaee-examples-master/target/payara5/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.548 s <<< FAILURE! - in jakartaee.examples.beanvalidation.notnull.NotNullBeanTest
[ERROR] testNotNullBean(jakartaee.examples.beanvalidation.notnull.NotNullBeanTest)  Time elapsed: 1.603 s  <<< FAILURE!
java.lang.AssertionError
	at jakartaee.examples.beanvalidation.notnull.NotNullBeanTest.testNotNullBean(NotNullBeanTest.java:96)


```

I'm using payara5:

```
mvn test -Ppayara5
```

I didn't investigated it further, just ran the test.

**Comment by manorrock** [comment] 2018-09-08 13:32
I am unable to reproduce with a full rebuild using either:

mvn clean install -P glassfish5

or:

mvn clean install -P payara5

Closing it out, but feel free to comment if the problem does persist

**Closed by manorrock** 2018-09-08 13:32 UTC

**Comment by rmpestano** [comment] 2018-09-11 15:31
Hi @manorrock,

I've investigated a little bit and the error is due to internationalization. The locale is being picked from my JVM/OS:

![notnull-i18n](https://user-images.githubusercontent.com/1592273/45370414-97344900-b5be-11e8-93a1-c41d400ec955.png)

To fix this we'd need to use a resource bundle on the page and also the same bundle on the tests.

**Comment by manorrock** [comment] 2018-09-12 22:06
Thanks for giving me more details. I will fix the test to use a specific locale.
